- pom.xml
- src/main/java/com/ericsson/ec/JenkinsManager.java
- src/main/java/com/ericsson/ec/helpers/JenkinsXmlData.java
- src/main/java/com/ericsson/ec/helpers/MediaType.java
- src/main/java/com/ericsson/ec/utils/HttpExecutor.java
- src/main/java/com/ericsson/ec/utils/HttpRequest.java
- src/main/java/com/ericsson/ec/utils/ResponseEntity.java
- src/main/java/com/ericsson/ec/utils/Utils.java
- src/test/java/com/ericsson/ec/jenkins_manager_test/JenkinsManagerExecutionTest.java
* Added return statement to return this class for JenkinsXmlData
this enables re use of class, example:
jenkinsData.addParameter(parram1).addParameter(param2);
(c) The …
> Renamed packages and add return statement

- src/main/java/com/ericsson/ec/helpers/JenkinsXmlData.java
> test new template path

- pom.xml
- src/main/java/com/ericsson/ec/helpers/JenkinsXmlData.java
- src/main/java/com/ericsson/ec/utils/Utils.java
> Fix template path

- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/SubscriptionObject.java
> made subscriptionobject public

- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/SubscriptionObject.java
- src/main/resources/subscriptionsTemplate.json
> Subscription object to public

- src/main/java/com/ericsson/ec/JenkinsManager.java
- src/main/java/com/ericsson/ec/helpers/JenkinsXmlData.java
- src/main/java/com/ericsson/ec/utils/HttpExecutor.java
- src/main/java/com/ericsson/ec/utils/HttpRequest.java
- src/main/java/com/ericsson/ec/utils/ResponseEntity.java
- src/main/java/com/ericsson/ec/utils/Utils.java
- src/test/java/com/ericsson/ec/jenkins_manager_test/JenkinsManagerExecutionTest.java
Needed in the integration test for eiffel-intelligence-frontend.
person who certified (a), (b) or (c) and I …
> Add remove header function in HttpRequest

- src/main/java/com/ericsson/eiffelcommons/JenkinsManager.java
- src/main/java/com/ericsson/eiffelcommons/utils/HttpRequest.java
- force creation gave an error if it failed removing a job.
It should not fail but it should instead create a job.
- Add javadoc for baseUrl getter/setter in HttpRequest …
> Fix force creatation of jobs in jenkinsmanager

- src/main/java/com/ericsson/eiffelcommons/utils/HttpRequest.java
Fix chaining for getter/setter baseUrl
it.
(d) …
> Fix chaining for getter/setter baseUrl

- src/main/java/com/ericsson/eiffelcommons/JenkinsManager.java
- src/main/java/com/ericsson/eiffelcommons/utils/Utils.java
> Removed some System.out.println

- pom.xml
> updated pom file

- src/main/java/com/ericsson/eiffelcommons/utils/HttpExecutor.java
- src/main/java/com/ericsson/eiffelcommons/utils/HttpRequest.java
- src/main/java/com/ericsson/eiffelcommons/utils/ResponseEntity.java
> Allow null body in response entity and persistent client true or false

- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/RestPostSubscriptionObject.java
Unable do use the new BASIC_AUTH_JENKINS_XXXX field in subscriptions
Authorizationtype and username and passwords will be set by 2 different functions.
(c) The …
> Enable use of custom AuthenticationType

- pom.xml
- src/main/java/com/ericsson/eiffelcommons/utils/HttpExecutor.java
- src/main/java/com/ericsson/eiffelcommons/utils/HttpRequest.java
- HttpRequest is now mockable by defining new ways of
initializing the class.
- HttpMethod can now be set after initializing as well.
This makes it possible for spring to autowire in a class
while different member functions still can execute
different types of requests.
- Headers can now be set in request body.
- URI can now be retrieved from HttpRequest.
work …
> Fix HttpRequest and HttpExecutor to be testable

- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/MailSubscriptionObject.java
- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/SubscriptionObject.java
- src/test/java/com/ericsson/eiffelcommons/subscriptionobjecttest/SubscriptionObjectTest.java
Add email subject to mail object and also a quick function to add a body.
person who certified (a), (b) or …
> Add some missing functions to support mail subject and body

- README.md
Add Jitpack badge to README.md
it.
(d) I …
> Add Travis and Jitpack badges

- .codacy.yaml
- .travis.yml
- README.md
- pom.xml
No code style or coverage checks.
- Add Codacy badgers in README.md
- Add codacy test coverage
- Add codacy code style check
(c) The contribution was provided directly to …
> Add codacy style check and test coverage

- pom.xml
- src/test/java/com/ericsson/eiffelcommons/httptest/HttpExecutorTest.java
- src/test/java/com/ericsson/eiffelcommons/httptest/HttpRequestTest.java
> Update json version

- src/main/java/com/ericsson/eiffelcommons/constants/MediaType.java
- src/main/java/com/ericsson/eiffelcommons/constants/RegExProvider.java
- src/main/java/com/ericsson/eiffelcommons/jenkins/JenkinsManager.java
- src/main/java/com/ericsson/eiffelcommons/jenkins/JenkinsXmlData.java
- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/SubscriptionObject.java
- src/main/java/com/ericsson/eiffelcommons/utils/FileUtils.java
- src/test/java/com/ericsson/eiffelcommons/constants/RegExProviderTest.java
- src/test/java/com/ericsson/eiffelcommons/http/HttpExecutorTest.java
- src/test/java/com/ericsson/eiffelcommons/http/HttpRequestTest.java
- src/test/java/com/ericsson/eiffelcommons/http/ResponseEntityTest.java
- src/test/java/com/ericsson/eiffelcommons/jenkins/JenkinsManagerExecutionTest.java
- src/test/java/com/ericsson/eiffelcommons/subscriptionobject/SubscriptionObjectTest.java
Restructure the packages a bit.
Give feedback if you have other ideas.
person who certified (a), (b) or (c) …
> Reorganize packages

- src/main/java/com/ericsson/eiffelcommons/constants/RegExProvider.java
- src/main/java/com/ericsson/eiffelcommons/exceptions/JenkinsManagerException.java
- src/main/java/com/ericsson/eiffelcommons/http/HttpRequest.java
- src/main/java/com/ericsson/eiffelcommons/jenkins/JenkinsManager.java
- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/MailSubscriptionObject.java
- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/RestPostSubscriptionObject.java
- src/main/java/com/ericsson/eiffelcommons/subscriptionobject/SubscriptionObject.java
- src/test/java/com/ericsson/eiffelcommons/jenkins/JenkinsManagerExecutionTest.java
- src/test/java/com/ericsson/eiffelcommons/jenkins/JenkinsManagerTest.java
- src/test/java/com/ericsson/eiffelcommons/utils/FileUtilsTest.java
- src/test/resources/json-array.json
Low codacy test percentage.
Added some more coverage.
Should up the percentage from 30% to 60%
The method buildJobWithFormPostParams in JenkinsManager does not appear to work as intended.
permitted to submit under a different license), as …
> Add more test coverage

- .github/dependabot.yml
Added dependabot.yml for alerts in github actions
person who certified (a), (b) or (c) and I have not …
> Added dependabot.yml for github actions

- jitpack.yml
Create jitpack.yml with 8.0.212-tem openjdk …
> Create jitpack.yml with 8.0.212-tem openjdk

- jitpack.yml
Ensure Eclipse Temurin is used to build the library
person who certified (a), (b) or (c) and I have not …
> Introduce jitpack.yml with Eclipse Temurin 17.0.5

- pom.xml
Prepare release for 1.0.4
Update pom with artifact id as eiffel-commons
person who certified (a), (b) or …
> Prepare release for 1.0.4
